name: ci
on:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - '**.md'

jobs:
  build-and-check:
    name: Build project and run CI checks
    uses: fingerprintjs/dx-team-toolkit/.github/workflows/build-typescript-project.yml@v1
