name: npm-publish
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  npm-publish:
    name: npm-publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: nodemodules-${{ hashFiles('yarn.lock') }}
          restore-keys: nodemodules-
      - name: Test
        uses: fingerprintjs/fingerprintjs-spa/.github/workflows/test.yml@test
      - name: Install Node packages
        run: yarn install
      - name: Build
        run: yarn build
      - name: Publish if version has been updated
        uses: pascalgn/npm-publish-action@1.3.8
        with:
          tag_name: "v%s"
          tag_message: "v%s"
          commit_pattern: "^Release (\\S+)"
          publish_command: "yarn"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
