name: release
on:
  push:
    branches:
      - main
      - test

jobs:
  build-and-check:
    name: 'Build project and run CI checks'
    uses: fingerprintjs/dx-team-toolkit/.github/workflows/build-typescript-project.yml@v1
    with:
      artifactName: 'fingerprintjs-pro-spa-artifact'
      path: |
        ./dist
        ./node_modules

  release:
    name: 'Release'
    needs: build-and-check
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: 'Download artifacts'
        uses: actions/download-artifact@v3
        with:
          name: 'fingerprintjs-pro-spa-artifact'

      - name: 'Release'
        run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          HUSKY: 0

